#!/bin/bash

rm ./builds/build*/CMakeCache.txt
rm -rf ./builds/build*/CMakeFiles
rm ./builds/build*/CMakeLists.txt
rm ./builds/build*/cmake_install.cmake

rm ./builds/build*/build*/CMakeCache.txt
rm -rf ./builds/build*/build*/CMakeFiles
rm ./builds/build*/build*/CMakeLists.txt
rm ./builds/build*/build*/cmake_install.cmake
