(* ::Package:: *)

(* ::Input:: *)
(*opt2d={{PlotRange->Automatic,*)
(*BaseStyle->Directive[FontFamily->"Times",FontSize->18],*)
(*PlotTheme->"Scientific",*)
(*Joined->True,*)
(*ImageSize->Medium,*)
(*FrameStyle->Directive[Black]*)
(*},{PlotRange->Automatic,*)
(*BaseStyle->Directive[FontFamily->"Times",FontSize->18],*)
(*PlotTheme->"Scientific",*)
(*Joined->True,*)
(*ImageSize->Medium,*)
(*FrameStyle->Directive[Black]*)
(*}};*)
