#!/bin/bash
# swap.sh - Swap the names of two files

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <filename_A> <filename_B>"
    exit 1
fi

filename_A="$1"
filename_B="$2"
tmp_name="filename_A_tmp"

mv "$filename_B" "$tmp_name"
mv "$filename_A" "$filename_B"
mv "$tmp_name" "$filename_A"
